Repository zer0Kerbal/Taerobee, pull requests merged in 2022-01, with the labels that each got.

#51 Create EnginesPlumeSWE.cfg
  GameData/Taerobee/Compatibility/Waterfall/EnginesPlumeSWE.cfg
Labels: issue: compatibility/patch, issue: config, type: feature, type: request, state: approved

#53 upstream changes
  .github/settings.yml
  doc/ReleaseNotes/1.3.9.9.htm
Labels: type: upstream

#74 X1 updates
  .github/.imgbotconfig
  GameData/Taerobee/Parts/X1/X1-body.cfg
  GameData/Taerobee/Parts/X1/X1-crew.cfg
  GameData/Taerobee/Parts/X1/X1-engine.cfg
  GameData/Taerobee/Parts/X1/X1-tail.cfg
Labels: issue: config, type: fix

#86 Update Bumper
  GameData/Taerobee/Parts/Bumper/bumper-body.cfg
  GameData/Taerobee/Parts/Bumper/bumper-control.cfg
  GameData/Taerobee/Parts/Bumper/bumper-engine-unclad.cfg
  GameData/Taerobee/Parts/Bumper/bumper-engine.cfg
  GameData/Taerobee/Parts/Bumper/bumper-fin.cfg
  GameData/Taerobee/Parts/Bumper/bumper-nose.cfg
Labels: issue: config

#101 Update taerobee 1.4.0.0
  GameData/Taerobee/Localization/en-us.cfg
  GameData/Taerobee/Parts/@thumbs/tbee-taerobee-adapter-short_icon0.png
  GameData/Taerobee/Parts/@thumbs/tbee-taerobee-adapter-tall_icon0.png
  GameData/Taerobee/Parts/Aerobee/taerobee-adapter-short.cfg
  GameData/Taerobee/Parts/Aerobee/taerobee-adapter-tall.cfg
  GameData/Taerobee/Parts/Aerobee/taerobee-aerobee.cfg
  GameData/Taerobee/Parts/Aerobee/taerobee-control.cfg
  GameData/Taerobee/Parts/Aerobee/taerobee-decoupler.cfg
  GameData/Taerobee/Parts/Aerobee/taerobee-despin.cfg
  GameData/Taerobee/Parts/Aerobee/taerobee-fin-large.cfg
  GameData/Taerobee/Parts/Aerobee/taerobee-fin-small.cfg
  GameData/Taerobee/Parts/Aerobee/taerobee-nosecone.cfg
  GameData/Taerobee/Parts/Aerobee/taerobee-parachute.cfg
  GameData/Taerobee/Parts/Aerobee/taerobee-science.cfg
  GameData/Taerobee/Parts/Aerobee/taerobee-sustainertank-3.cfg
  GameData/Taerobee/Parts/Aerobee/taerobee-tinytim.cfg
  GameData/Taerobee/changelog.md
  Thumper FT-u2x = 2_4m x 0_625_.2do
Labels: issue: config
